
export default function getGlobalVar(){
    return {
     listForm : document.getElementById('list-form'),
     newListBtn : document.getElementById('newList'),
     listName : document.getElementById('list-name'),
     searchBtn : document.getElementById('searchBtn'),
     searchForm : document.getElementById('search-form'),
     searchName : document.getElementById('search-name'),
     selectedTask : document.getElementById('selTask'),
     renameDiv : document.getElementById('rename-list'),
     mainDivList: document.getElementById('main-div-list'),
     listBlock : document.querySelector('.list-container'),
     btnGroup : document.querySelector('.btn-group'),
     taskName : document.getElementById('task-name'),
     taskList : document.querySelector('.show-taskList'),
     taskDiv2 : document.getElementById('task-div-2'),
     taskNotes : document.getElementById('task-note'),
     dueDate : document.getElementById('due-date'),
     priority : document.getElementById('prId'),
     moreInfoBtn : document.getElementById('more-info-btn'),
     moreInfo : document.querySelector('.show-more-info'),
     taskDiv : document.querySelector('.task-div'),
     schNav : document.getElementById('sch-id'),
     filterBtn : document.getElementById('filterBtn'),
     todayBlock : document.querySelector('.today-container'),
     todayDiv : document.getElementById('today-task'),
     schBlock : document.querySelector('.sch-container'),
     schDiv : document.getElementById('sch-task'),
     listNav : document.getElementById('list-id'),
     todayNav : document.getElementById('today-id'),
     goBackBtn : document.getElementById('goBack'),
     header : document.getElementById('myDIV'),
     btns : document.getElementsByClassName("block-2"),
     crListItem:document.getElementById('crListBtn'),
     srListItem:document.getElementById('srListBtn'),
     upTaskBtn:document.getElementById('upTaskBtn'),
     delTaskBtn:document.getElementById('delTaskBtn'),
     nav1:document.getElementById('nav-1'),
     nav2:document.getElementById('nav-2')
    }
}